# Generated by Django 3.2 on 2021-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
